### ISSUE TITLE
Doesn´t log properly

### ISSUE THREAD

**Issue by KaikiFather** [notunixian/ares_logger#3]
First time when i ran it with older versions, the logger worked fine.
But when i tried in another computer, the driver, the injector and the console window works fine, but when i go to worlds or see the avatares the logger doesn´t work.

I took a look at the VRChat root folder, the ares_logger folder has been created correctly, but it is empty, without any files.

**Comment by notunixian** [comment]
https://i.imgur.com/JJIcBhb.png
seems to work fine for me, you might be missing the json dependency

**Comment by KaikiFather** [comment]
Yup in the other computer still working fine, but in this new, after a few tries still withouth creating the jsons and not just that, in the console window, the logs never appear.  Only shows the authcookie and other information but no logs.
Happened to other friends too and i don´t know why.

**Comment by notunixian** [comment]
use latest loader, seems like you are missing the json dependency if it's not creating it

**Comment by KaikiFather** [comment]
Yup, i can confirm that i wasn´t using the last loader. Now it works. Thank you for your assist.
